djangogram/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from dg import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register_user, name='register'),
    path('', views.home_page, name='index'),
    path('sendmessage/', views.send_message, name='send_message'),
    path('newchat/', views.new_chat),
    path('global_chat/', views.global_chat, name='global_chat'),
    path('get_messages/', views.get_messages),
    path('get_global_messages/', views.get_global_msgs),
    path('coverage/', views.coverage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns =   [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

dg/models.py
"""This module describes models"""
from django.db import models
import os
from PIL import Image




class Chat(models.Model):
    """This is Chat model"""
    uid1 = models.IntegerField()
    uid2 = models.IntegerField()


class GlobalChat(models.Model):
    """This is GlobalChat model"""
    sender_username = models.CharField(max_length=1000)
    text = models.CharField(max_length=2500)
    time = models.TimeField()


class MessageFile(models.Model):
    """This is files attached to global chat model"""
    file = models.FileField(upload_to="global_chat", blank=True, null=True, default=None)
    name = models.CharField(max_length=50, null=True, blank=True, default=None)
    size = models.IntegerField(null=True, blank=True, default=None)
    message = models.ForeignKey(GlobalChat, on_delete=models.SET_NULL, null=True, blank=True, default=None,
                                related_name='files')

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def is_image(self):
        extension = self.extension()
        if extension in ['.jpg', '.jpeg', '.png']:
            return True
        return False


class Message(models.Model):
    """This is Message model"""
    text = models.CharField(max_length=500)
    chat_id = models.IntegerField()
    sender_id = models.IntegerField()
    time = models.DateTimeField()


class MessageFileDirect(models.Model):
    """This is files attached to direct chat model"""
    file = models.FileField(upload_to="direct_chat", blank=True, null=True, default=None)
    name = models.CharField(max_length=50, null=True, blank=True, default=None)
    size = models.IntegerField(null=True, blank=True, default=None)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, blank=True, default=None,
                                related_name='files')

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def is_image(self):
        extension = self.extension()
        if extension in ['.jpg', '.jpeg', '.png']:
            return True
        return False


class UserBalance(models.Model):
    """This is Balance model"""
    user_id = models.IntegerField()
    money = models.IntegerField()


class ShopKeys(models.Model):
    """This is keys model"""
    key = models.CharField(max_length=100)
    money = models.IntegerField()
    status = models.IntegerField()

dg/forms.py
"""This module describes forms"""
from django import forms
from django.contrib.auth.models import User


class SendMessageFrom(forms.Form):
    """This is send message form"""
    text = forms.CharField(max_length=500, required=False)
    chat_id = forms.IntegerField()
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    def clean(self):
        text = self.cleaned_data.get('text')
        chat_id = self.cleaned_data.get('chat_id')
        files = self.cleaned_data.get('files')
        if not text and not files:
            raise forms.ValidationError('Empty message')
        return self.cleaned_data


class ChangePasswordForm(forms.Form):
    """This is change password form"""
    old_password = forms.CharField(max_length=500)
    new_password = forms.CharField(max_length=500)


class CreateChatForm(forms.Form):
    """This is create chat form"""
    user_to = forms.CharField(max_length=1000, label='')


class UserRegistrationForm(forms.ModelForm):
    """This is user registrations form"""
    """This class provide you an opportunity to register on the site
        fields:
        password - password to your account
        password2 - repeat the password
        methods:
        clean_password2 - function that clean the field? if the passwords didn`t match
    """
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        """This class adds you a username"""
        model = User
        fields = ('username',)

    def clean_password2(self):
        """This function cleans your password"""
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class GlobalChatForm(forms.Form):
    """This is send message form"""
    text = forms.CharField(max_length=1000, required=False, label='')
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False, label='')


class Buy(forms.Form):
    """This is buy form"""
    key = forms.CharField(max_length=100)

dg/views.py
"""This module describes main logic of server"""
import datetime
import json
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.defaulttags import register
from django.views.decorators.http import require_http_methods
from dg.models import *
from dg.forms import *
from django.contrib import messages


@register.filter
def get_item(dictionary, key):
    """This function returns dictionary value by key"""
    return dictionary[key]


def get_base_context(request):
    """This function returns base page"""
    menu = [
        {"link": "/", "text": "Главная"},
        {"link": "/global_chat", "text": "Глобальный чат"},
    ]

    if request.user.is_authenticated:
        menu.append({"link": "/profile", "text": "Профиль"})
        menu.append({"link": "/logout", "text": "Выход"})
    else:
        menu.append({"link": "/login", "text": "Вход"})
        menu.append({"link": "/register", "text": "Регистрация"})

    context = {'menu': menu, 'error': ''}
    return context


def home_page(request):
    """This function renders main page"""
    context = get_base_context(request)
    if not request.user.is_authenticated:
        return redirect('/login')
    if request.method == 'GET':
        chats1 = Chat.objects.all().filter(uid1=request.user.id)
        chats2 = Chat.objects.all().filter(uid2=request.user.id)
        chats = chats1.union(chats2)
        context['chats'] = chats
        names = {}
        for chat in chats:
            if chat.uid1 == request.user.id:
                names[chat.id] = User.objects.all().filter(id=chat.uid2)[0].username
            elif chat.uid2 == request.user.id:
                names[chat.id] = User.objects.all().filter(id=chat.uid1)[0].username
        context['names'] = names
        messages = {}
        ids = []
        usernames = {}
        last_messages = {}
        for chat in chats:
            if Message.objects.all().filter(chat_id=chat.id):
                last_messages[chat.id] = Message.objects.all().filter(chat_id=chat.id)[0].time
            messages_new = []
            for message in Message.objects.all().filter(chat_id=chat.id):
                messages_new.append(message)
            ids.append(str(chat.id))
            messages[str(chat.id)] = messages_new
            usernames[chat.uid1] = User.objects.all().filter(id=chat.uid1)[0].username
            usernames[chat.uid2] = User.objects.all().filter(id=chat.uid2)[0].username
        context['usernames'] = usernames
        context['ids'] = ids
        context['messages'] = messages
        context['newchatform'] = CreateChatForm()
        context['sendmessageform'] = SendMessageFrom()
        context['last_messages'] = last_messages
    return render(request, "index.html", context)


def register_user(request):
    """function returns register page(/register) to the client and saves new users

    :request: variable containing http parameters
    """
    context = {}
    context['invalid_register'] = ""
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            new_balance = UserBalance(
                user_id=new_user.id,
                money=0)
            new_balance.save()
            context["balance"] = new_balance
            return redirect('/login')
        if User.objects.filter(username=user_form.data.get('username')).exists():
            context['invalid_register'] += "User with this username already exists\n"
        if user_form.data.get('password') != user_form.data.get('password2'):
            context['invalid_register'] += "Passwords don't match\n"
    else:
        user_form = UserRegistrationForm()
        context['user_form'] = user_form
    return render(request, 'registration/register.html', context)


def profile(request):
    """This function renders profile page"""
    context = get_base_context(request)
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            if request.user.check_password(form.data.get('old_password')):
                user = User.objects.get(username__exact=request.user.username)
                user.set_password(form.data.get('new_password'))
                user.save()
            else:
                context['error'] = ("You forgot to fill in the password field.")
        return redirect('/logout')
    if not request.user.is_authenticated:
        return redirect('/login')
    change_pass_form = ChangePasswordForm()
    user_balance = UserBalance.objects.all().filter(user_id=request.user.id)[0].money
    context = {'user': request.user, 'change_pass_form':
        change_pass_form, 'user_balance': user_balance}
    return render(request, 'profile.html', context)


@login_required
def send_message(request):
    """This function renders send_message request"""
    context = get_base_context(request)
    if request.method == 'POST':
        user_form = SendMessageFrom(request.POST)
        chat_id = user_form.data.get('chat_id')
        chat = Chat.objects.all().filter(id=chat_id)
        if chat_id != '':
            request_files = request.FILES.getlist('files')
            if not chat:
                context['error'] = 'No such chat'
            chat = chat[0]
            if request.user.id not in (chat.uid1, chat.uid2):
                context['error'] = 'No such chat'
            if user_form.is_valid() or request_files:
                new_field = Message(time=datetime.datetime.now(),
                                    chat_id=chat.id, sender_id=request.user.id,
                                    text=user_form.data.get('text'))
                new_field.save()
                for f in request_files:
                    file = MessageFileDirect(file=f, message=new_field, name=f.name, size=(f.size / 1000))
                    file.save()
    return redirect('/')


@require_http_methods(["POST"])
def new_chat(request):
    """This function processes newChat request"""
    context = get_base_context(request)
    if request.method == 'POST':
        user_form = CreateChatForm(request.POST)
        if user_form.is_valid():
            if not User.objects.all().filter(username=user_form.data.get('user_to')):
                context['error'] = 'No such user'
            else:
                secondusername = user_form.data.get('user_to')
                existing_chats = Chat.objects.all().filter(uid1=request.user.id,
                                                           uid2=User.objects.all().filter(
                                                               username=secondusername)[
                                                               0].id) | \
                                 Chat.objects.all().filter(
                                     uid2=request.user.id,
                                     uid1=User.objects.all().filter(username=secondusername)[0].id)
                if len(existing_chats) != 0:
                    context['error'] = 'Chat already exists'
                    return redirect('/', context=context)
                new_field = Chat(uid1=request.user.id,
                                 uid2=User.objects.all().filter(username=secondusername)[0].id)
                new_field.save()
    return redirect('/')


def global_chat(request):
    """This function renders global chat page"""
    context = {}
    if request.method == "POST":
        form = GlobalChatForm(request.POST)
        request_files = request.FILES.getlist('files')
        if form.data['text'] or request_files:
            if request.user.is_authenticated:
                new_message = GlobalChat(
                    sender_username=request.user.username,
                    text=form.data["text"],
                    time=datetime.datetime.now()
                )
            else:
                new_message = GlobalChat(
                    sender_username='Anonymous',
                    text=form.data["text"],
                    time=datetime.datetime.now()
                )
            new_message.save()
            for f in request_files:
                # f.name = f.name.replace("global_chat/","")
                # print(f.name)

                file = MessageFile(file=f, message=new_message, name=f.name, size=(f.size / 1000))
                file.save()

    form = GlobalChatForm()
    context = {"form": form}
    all_messages = GlobalChat.objects.all()
    msgs = []
    for i in range(len(all_messages) - 1, 0, -1):
        msgs.append(all_messages[i])
    context["messages"] = msgs
    context.update(get_base_context(request))
    return render(request, "global_chat.html", context)


def shop(request):
    """This function renders shop page"""
    context = {}
    all_balances = UserBalance.objects.all()
    flag_user = False
    if request.user.is_authenticated:
        for balance in all_balances:
            if balance.user_id == request.user.id:
                flag_user = True
                context["balance"] = balance
                break
        if not flag_user:
            new_balance = UserBalance(
                user_id=request.user.id,
                money=0)
            new_balance.save()
            context["balance"] = new_balance
    else:
        no_balance = UserBalance(
            user_id=-1,
            money=-1)
        context["balance"] = no_balance
    context.update(get_base_context(request))
    context["user"] = request.user

dg/templates/global_chat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <meta charset="UTF-8">
    <title>Глобальный чат</title>
</head>
<body>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>setInterval(function(){
    load();
}, 1000);</script>
<script>
    function load() {
        $.ajax({
            url: "/get_global_messages",
            success: function (data) {
                $('#msgs').html('')
                let msgs = data;
                for(let i = 0; i < data.length; i++){
                    msg = msgs[i]
                    if (i.file === '0') {
                        $('#msgs').append('<div><div class="msg"><strong>' + msg.sender + '</strong><br>' + msg.text + '<span><strong>' + msg.time + '</strong></span> <br/>')
                    }
                    else if (i.is_image === 1) {
                        $('#msgs').append('<div><div class="msg"><strong>' + msg.sender + '</strong><br>' + msg.text + '<span><strong>' + msg.time + '</strong></span> <br/>' + '<a style="color:blue;" href="/media/global_chat/' + msg.file + '">Скачать</a>' + '<img src = "/media/global_chat/' + i.file + '" class = "img-thumbnail"/> <br/>')
                    }
                    else {
                        $('#msgs').append('<div><div class="msg"><strong>' + msg.sender + '</strong><br>' + msg.text + '<span><strong>' + msg.time + '</strong></span> <br/>' + '<a style="color:blue;" href="/media/global_chat/' + msg.file + '">Скачать</a>')
                    }
                }

            }
        });
    }
</script> !-->
    <div class="preloader">

    </div>
    <div>
        <div class="menu">
            <div class="mainnav">
                <div>
                </div>
                <h1>Global Chat</h1>
                <a href="#" class="menu-btn"></a>
                <ul class="menu-ul">
                    <li>
                        <a href="{% url 'index' %}"> ГЛАВНАЯ</a>
                    </li>
                    <li>
                        <a href="{% url 'profile' %}"> ПРОФИЛЬ</a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}"> ВОЙТИ</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}"> ВЫЙТИ</a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}"> РЕГИСТРАЦИЯ</a>
                    </li>

                </ul>
            </div>
        </div>
        <div class="content">
            <div id = "msgs" class="msgs">
                {% for i in messages %}
            <div>
                <!--<a><img src="{{MEDIA_URL}}avatars/default.png"></a>-->
                <div class="msg">
                    <strong>{{ i.sender_username }}</strong><br>{{ i.text }}<span><strong> {{ i.time }}</strong></span> <br/>
                    {% for file in i.files.all %}
                        {% if file.is_image %}
                            <img src = "{{file.file.url}}" class = "img-thumbnail"/> <br/>
                        {% endif %}
                        <a style="color: blue;" href = "{{ file.file.url }}">Скачать файл {{ file.name }} (вес {{ file.size }} КБ)</a> <br/>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <br><br><br>
            </div>
            <div class="form">
                <form action="/global_chat/" method="post" enctype="multipart/form-data">
                        <div>
                            <label class="custom-file-upload">
                                {% csrf_token %}
                                {{ form }}
                            </label>
                        </div>
                        <div>
                            <button class="btn" type="submit"></button>
                        </div>
                </form>
            </div>
        </div>
    </div>
<style>
    body{
        font-family: Arial;
        background-color: #d3d3d3;
    }
    body:hover{
    }
    a{
      text-decoration: none;
      color:white;
      display:flex;
    }
    a:visited{
        color:none;
      }
    a:focus{
        color:none;
    }
    a:hover{
        color:none;
      }
    a:hover, a:active{
        color:none;
    }
    ul{
        list-style: none;
    }
    img{
        max-height: 30vh;
    }
    .msg{
        font-size: 16px;
        background-color: white;
        border-radius: 10px;
        padding-left: 20px;
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 20px;
        padding-right: 20px;
        display: inline-block;
        margin-bottom: 10px;
        margin-left: 25px;
        max-width: 50%;
        word-wrap: break-word;
    }
    .msgs{
        margin-left: 25%;
    }
    .form{
        height: 5%;
        position: fixed;
        bottom: 0px;
        background-color: #d3d3d3;
        width: 100%;
        left: 0px;
        text-align: center;
        padding: 10px;
    }
    form{
        height: 100%;
        display: flex;
        justify-content: center;
    }
    .content{
        margin: 0 auto;
    }
    span{
        color: gray;
        font-size: 10px;
    }
    #id_text {
        outline: none;
    }
    .mainnav{
      display: flex;
      align-items: center;
    }
    .mainnav ul li{
      display: inline-block;
    }
    .menu{
        display: inline-block;
        color: white;
        background-color: #ef233c;
        position: fixed;
        top: 0;
        width: 100%;
        left: 0px;
        transform: translateY(-100%);
        transition: 0.5s;
        float:left;
    }
    .menu_active {
        transform: translateY(0%);
    }
    .menu-btn{
          width: 60px;
          height: 60px;
          background-color: #ef233c;
          position: absolute;
          bottom: -50px;
          z-index: -100;
          right: 0;
          border-radius: 50% 0% 50% 50% / 0% 50% 50% 50%;
    }
    .menu-btn:hover{
	      transition: 0.5s;
          color: #29648A;
    }
    .menu-btn::after{
      position: absolute;
      content: '';
      top: 52.5%;
      left: 50%;
      width: 15px;
      height: 15px;
      border-color: black;
      border-top: 5px solid;
      border-left: 5px solid;
      transform: translate(-50%, -50%) rotate(225deg);
      transition: 0.5s;
    }
    .menu-ul{
        position: relative;
    }
    .content{
    }
    h1{
        margin-left: 10px;
    }
    .btn{
        position: relative;
        right: calc(50% - 50px / 2 + 30px);
        background-color: white;
        width: 50px;
        height: 105%;
        border: none;
        border-radius: 0% 50% 50% 0% / 0% 50% 50% 0%;
        transition: 0.5s;
        transform: translateX(-50px);
    }
    .btn:hover {
        transition: 0.5s;
        background-color: lightgray;
    }
    input{
        position: relative;
        width: 450px;
        left: calc(50% - 450px / 2 - 50px / 2 - 5px);
        border: white;
        font-size: 16px;
        top: 0px;
        height: 100%;
    }
    #id_files {
        position: relative;
        background-color: white;
        width: 50px;
        height: calc(105% + 0.5px);
        border: none;
        border-radius: 50% 0% 0% 50% / 50% 0% 0% 50%;
        transition: 0.5s;
        z-index: 101;
        text-indent: -999em;
        transform: translateY(-8px) translateX(-508px);
    }
    #id_files:hover{
        transition: background-color 0.5s;
        background-color: lightgray;
    }
    .preloader{
      background-color: white;
      background-image: url("{% static 'dgram.jpg'%}");
      background-position: center;
      background-size: 9%;
      position: fixed;
      top: 0;
      left: 0;
      z-index: 100;
      width: 100%;
      height: 100%;
      background-repeat: no-repeat;
      animation-iteration-count: infinite;
      animation-duration: 0.5s;
      animation-name: preloader-scale;
    }
    @keyframes preloader-scale{
      from{
        transform: scale(1.0);
      }
      50%{
        transform: scale(1.5)
      }
      to{
        transform: scale(1.0);
      }
    }
</style>
<script>
  $('.menu-btn').on('click', function(e) {
  e.preventDefault();
  $('.menu').toggleClass('menu_active');
  $('.content').toggleClass('content_active');
})

setTimeout(() => {
    document.querySelector("body").classList.remove();
    document.querySelector(".preloader").remove();
}, 600)
</script>
</body>
</html>

dg/templates/index.html
{% load static %}
<html lang="ru">
<head>
    <title>DjangoGram</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'icon1.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>.tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }</style>
</head>
<body>
<script>window.onload = function() {
  load();
};</script>
<script>
        function scrollDown() {
            tabcontent = document.getElementsByClassName("tabcontent");
            for (var i = 0; i < tabcontent.length; i++) {
                tabcontent[i].scrollTop = tabcontent[i].scrollHeight;
            }
        }
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>setInterval(function () {
    load();
}, 5000);</script>
<script>
    function load() {
        $.ajax({
            url: "/get_messages",
            success: function (data) {
                let msgs = data.new_messages;
                let chats = data.chats;
                let new_strng = '';
                $('groups').html('')
                for (let i = 0; i < chats.length; i++){
                    $('groups').append('<button class="tablinks" onclick="openChat(event, "' +  chats[i].id  + '");scrollDown();"> <div class="group-container"> <img src="{{ MEDIA_URL }}avatars/default.png" class="group-icon"> <h2 class="group-title">' + chats[i].username + '</h2> </div> </button>')
                }
                for (let i = 0; i < msgs.length; i++) {
                    st = '#';
                    st += msgs[i].chat_id;
                    $(st).html('')
                }
                for (let i = 0; i < msgs.length; i++) {
                    st = '#';
                    st += msgs[i].chat_id;
                    msg = msgs[i];
                    if (msg.file_p === "0") {
                        $(st).append('<div class="msg"><h1 id="text">' + msgs[i].username + ': ' + msgs[i].text + '</h1>' + '<h3 id="time">' + msgs[i].time + '</h3>')
                    } else if (msg.is_image === true) {
                        $(st).append('<div class="msg"><h1 id="text">' + msgs[i].username + ': ' + msgs[i].text + '</h1>' + '<img src = "/media/direct_chat/' + msg.file_p + '" class = "img-thumbnail"/>'  + '<h3 id="time">' + msgs[i].time + '</h3>' + '<a style="color:blue;" href="/media/global_chat/' + msg.file + '">Скачать</a>')

                    } else {
                        $(st).append('<div class="msg"><h1 id="text">' + msgs[i].username + ': ' + msgs[i].text + '</h1>' + '<h3 id="time">' + msgs[i].time + '</h3>' + '<a style="color:blue;" href="/media/global_chat/' + msg.file + '">Скачать</a>')

                    }
                }
            }
        });
    }
</script>
<script src="{% static 'js/script.js' %}"></script>
<nav class="navbar-expand-lg navbar-light" style="background-color: #3f8ad1; width: 100%;">
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% for item in menu %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ item.link }}">{{ item.text }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</nav>
<div class="main-container">
    <div id="groups" class="groups-container">
        {% for chat in chats %}
            <button class="tablinks" onclick="openChat(event, '{{ chat.id }}');scrollDown();">
                <div class="group-container">
                    <img src="{{ MEDIA_URL }}avatars/default.png" class="group-icon">
                    <h2 class="group-title">{{ names|get_item:chat.id }}</h2>
                    </div>
            </button>
        {% endfor %}
        <div class="group-container">
            <form action="/newchat/" method="post">
                {% csrf_token %}
                <p>New chat</p>
                {{ newchatform }}
                <button>Submit</button>
            </form>
        </div>
    </div>
    <div class="chat-container" id="chats">
        {% for id in ids %}
            <div id="{{ id }}" class="tabcontent">
                {% for msg in messages|get_item:id %}
                    <div class="msg">
                        <h1 id="text">{{ usernames|get_item:msg.sender_id }}: {{ msg.text }}</h1>
                        <div style="font-size:20px;">
                            {% for file in msg.files.all %}
                                {% if file.is_image %}
                                    <img src="{{ file.file.url }}" class="img-thumbnail"/> <br/>
                                {% endif %}
                                <a href="{{ file.file.url }}">Скачать файл {{ file.name }} (вес {{ file.size }} КБ)</a>
                                <br/>
                            {% endfor %}
                        </div>
                        <h3 id="time">{{ msg.time }}</h3>
                    </div>

                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <form action="/sendmessage/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Text:
        <div class="mr-4"> {{ sendmessageform.text }} </div>
        <div> {{ sendmessageform.files }} </div>
        <input id="chat_id" type="hidden" name="chat_id" value="">
        <button onclick="getChat();">Отправить</button>
    </form>
</div>
</div>
</body>
</html>

dg/templates/msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="/sendmessage/" method="post">
        {% csrf_token %}
        {{ form }}
        <button>Send</button>
    </form>
</body>
</html>

dg/templates/newchat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New chat</title>
</head>
<body>
    <form action="/newchat/" method="post">
        {% csrf_token %}
        {{ form }}
        <button>ff</button>
    </form>
</body>
</html>